// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: adapterkit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Adapter(ctx context.Context, opts ...grpc.CallOption) (Service_AdapterClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Adapter(ctx context.Context, opts ...grpc.CallOption) (Service_AdapterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/Service/Adapter", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceAdapterClient{stream}
	return x, nil
}

type Service_AdapterClient interface {
	Send(*AdapterRequest) error
	Recv() (*AdapterResponse, error)
	grpc.ClientStream
}

type serviceAdapterClient struct {
	grpc.ClientStream
}

func (x *serviceAdapterClient) Send(m *AdapterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceAdapterClient) Recv() (*AdapterResponse, error) {
	m := new(AdapterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	Adapter(Service_AdapterServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Adapter(Service_AdapterServer) error {
	return status.Errorf(codes.Unimplemented, "method Adapter not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Adapter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).Adapter(&serviceAdapterServer{stream})
}

type Service_AdapterServer interface {
	Send(*AdapterResponse) error
	Recv() (*AdapterRequest, error)
	grpc.ServerStream
}

type serviceAdapterServer struct {
	grpc.ServerStream
}

func (x *serviceAdapterServer) Send(m *AdapterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceAdapterServer) Recv() (*AdapterRequest, error) {
	m := new(AdapterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Adapter",
			Handler:       _Service_Adapter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "adapterkit.proto",
}
