// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: adapterkit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdapterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *AdapterRequest) Reset() {
	*x = AdapterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapterkit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterRequest) ProtoMessage() {}

func (x *AdapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapterkit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterRequest.ProtoReflect.Descriptor instead.
func (*AdapterRequest) Descriptor() ([]byte, []int) {
	return file_adapterkit_proto_rawDescGZIP(), []int{0}
}

func (x *AdapterRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AdapterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *AdapterResponse) Reset() {
	*x = AdapterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapterkit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterResponse) ProtoMessage() {}

func (x *AdapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapterkit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterResponse.ProtoReflect.Descriptor instead.
func (*AdapterResponse) Descriptor() ([]byte, []int) {
	return file_adapterkit_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_adapterkit_proto protoreflect.FileDescriptor

var file_adapterkit_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x6b, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2b,
	0x0a, 0x0f, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x92, 0x01, 0x0a, 0x11,
	0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x4b, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3f, 0x0a, 0x14, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x41, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x3c, 0x0a, 0x15, 0x55, 0x6e, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x41, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41,
	0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adapterkit_proto_rawDescOnce sync.Once
	file_adapterkit_proto_rawDescData = file_adapterkit_proto_rawDesc
)

func file_adapterkit_proto_rawDescGZIP() []byte {
	file_adapterkit_proto_rawDescOnce.Do(func() {
		file_adapterkit_proto_rawDescData = protoimpl.X.CompressGZIP(file_adapterkit_proto_rawDescData)
	})
	return file_adapterkit_proto_rawDescData
}

var file_adapterkit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adapterkit_proto_goTypes = []interface{}{
	(*AdapterRequest)(nil),  // 0: AdapterRequest
	(*AdapterResponse)(nil), // 1: AdapterResponse
}
var file_adapterkit_proto_depIdxs = []int32{
	0, // 0: AdapterKitService.BiDirectionalAdapter:input_type -> AdapterRequest
	0, // 1: AdapterKitService.UniDirectionalAdapter:input_type -> AdapterRequest
	1, // 2: AdapterKitService.BiDirectionalAdapter:output_type -> AdapterResponse
	1, // 3: AdapterKitService.UniDirectionalAdapter:output_type -> AdapterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adapterkit_proto_init() }
func file_adapterkit_proto_init() {
	if File_adapterkit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adapterkit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdapterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapterkit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdapterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adapterkit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapterkit_proto_goTypes,
		DependencyIndexes: file_adapterkit_proto_depIdxs,
		MessageInfos:      file_adapterkit_proto_msgTypes,
	}.Build()
	File_adapterkit_proto = out.File
	file_adapterkit_proto_rawDesc = nil
	file_adapterkit_proto_goTypes = nil
	file_adapterkit_proto_depIdxs = nil
}
