// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: adapterkit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServClient is the client API for Serv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServClient interface {
	Adapter(ctx context.Context, opts ...grpc.CallOption) (Serv_AdapterClient, error)
}

type servClient struct {
	cc grpc.ClientConnInterface
}

func NewServClient(cc grpc.ClientConnInterface) ServClient {
	return &servClient{cc}
}

func (c *servClient) Adapter(ctx context.Context, opts ...grpc.CallOption) (Serv_AdapterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Serv_ServiceDesc.Streams[0], "/Serv/Adapter", opts...)
	if err != nil {
		return nil, err
	}
	x := &servAdapterClient{stream}
	return x, nil
}

type Serv_AdapterClient interface {
	Send(*AdapterRequest) error
	Recv() (*AdapterResponse, error)
	grpc.ClientStream
}

type servAdapterClient struct {
	grpc.ClientStream
}

func (x *servAdapterClient) Send(m *AdapterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *servAdapterClient) Recv() (*AdapterResponse, error) {
	m := new(AdapterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServServer is the server API for Serv service.
// All implementations must embed UnimplementedServServer
// for forward compatibility
type ServServer interface {
	Adapter(Serv_AdapterServer) error
	mustEmbedUnimplementedServServer()
}

// UnimplementedServServer must be embedded to have forward compatible implementations.
type UnimplementedServServer struct {
}

func (UnimplementedServServer) Adapter(Serv_AdapterServer) error {
	return status.Errorf(codes.Unimplemented, "method Adapter not implemented")
}
func (UnimplementedServServer) mustEmbedUnimplementedServServer() {}

// UnsafeServServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServServer will
// result in compilation errors.
type UnsafeServServer interface {
	mustEmbedUnimplementedServServer()
}

func RegisterServServer(s grpc.ServiceRegistrar, srv ServServer) {
	s.RegisterService(&Serv_ServiceDesc, srv)
}

func _Serv_Adapter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServServer).Adapter(&servAdapterServer{stream})
}

type Serv_AdapterServer interface {
	Send(*AdapterResponse) error
	Recv() (*AdapterRequest, error)
	grpc.ServerStream
}

type servAdapterServer struct {
	grpc.ServerStream
}

func (x *servAdapterServer) Send(m *AdapterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *servAdapterServer) Recv() (*AdapterRequest, error) {
	m := new(AdapterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Serv_ServiceDesc is the grpc.ServiceDesc for Serv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Serv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Serv",
	HandlerType: (*ServServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Adapter",
			Handler:       _Serv_Adapter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "adapterkit.proto",
}
