/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.3.1
// 	protoc              v3.20.1
// source: adapterkit.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./adapterkit_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.AdapterKitServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.AdapterKitServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.AdapterRequest,
 *   !proto.AdapterResponse>}
 */
const methodDescriptor_AdapterKitService_UniDirectionalAdapter = new grpc.web.MethodDescriptor(
  '/AdapterKitService/UniDirectionalAdapter',
  grpc.web.MethodType.UNARY,
  proto.AdapterRequest,
  proto.AdapterResponse,
  /**
   * @param {!proto.AdapterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.AdapterResponse.deserializeBinary
);


/**
 * @param {!proto.AdapterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.AdapterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.AdapterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.AdapterKitServiceClient.prototype.uniDirectionalAdapter =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/AdapterKitService/UniDirectionalAdapter',
      request,
      metadata || {},
      methodDescriptor_AdapterKitService_UniDirectionalAdapter,
      callback);
};


/**
 * @param {!proto.AdapterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.AdapterResponse>}
 *     Promise that resolves to the response
 */
proto.AdapterKitServicePromiseClient.prototype.uniDirectionalAdapter =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/AdapterKitService/UniDirectionalAdapter',
      request,
      metadata || {},
      methodDescriptor_AdapterKitService_UniDirectionalAdapter);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.AdapterRequest,
 *   !proto.AdapterResponse>}
 */
const methodDescriptor_AdapterKitService_ServerStreamingAdapter = new grpc.web.MethodDescriptor(
  '/AdapterKitService/ServerStreamingAdapter',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.AdapterRequest,
  proto.AdapterResponse,
  /**
   * @param {!proto.AdapterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.AdapterResponse.deserializeBinary
);


/**
 * @param {!proto.AdapterRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.AdapterResponse>}
 *     The XHR Node Readable Stream
 */
proto.AdapterKitServiceClient.prototype.serverStreamingAdapter =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/AdapterKitService/ServerStreamingAdapter',
      request,
      metadata || {},
      methodDescriptor_AdapterKitService_ServerStreamingAdapter);
};


/**
 * @param {!proto.AdapterRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.AdapterResponse>}
 *     The XHR Node Readable Stream
 */
proto.AdapterKitServicePromiseClient.prototype.serverStreamingAdapter =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/AdapterKitService/ServerStreamingAdapter',
      request,
      metadata || {},
      methodDescriptor_AdapterKitService_ServerStreamingAdapter);
};


module.exports = proto;

